server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
          - id: provider
            uri: http://localhost:8081
            order: 1
            predicates:
                - Path=/find/**
          - id: consumer
            uri: http://localhost:8082
            order: 1
            predicates:
                - Path=/search/**